trigger: none
pr: none

name: 'Build And Push SQL Deployment Container'

parameters:
- name: weatherAPIACRGroup
  displayName: Weather API ACR Variable Group
  type: string
  default: 'DEV ACR Variable Group'
  values:
  - 'DEV ACR Variable Group'
  - 'PROD ACR Variable Group'

variables:
- group: ${{ parameters.weatherAPIACRGroup }}
- name: linuxsqlpackage-imageRepository
  value: 'linuxsqlpackage'
- name: linuxsqlpackage-dockerfilePath
  value: '**/**/sql-package-linux-dockerfile'

- name: tag
  value: 'latest'

pool:
  name: '$(agent-pool)'

stages:
- stage: Build_WeatherAPI
  displayName: Build and push stage Weather API
  jobs:
  - job: Build_and_Push_WeatherAPI
    displayName: Build and Push Weather API
    steps:
     
    - task: Docker@2
      displayName: Build and Push SqlPackage
      inputs:
        command: buildAndPush
        repository: $(linuxsqlpackage-imageRepository)
        dockerfile: $(linuxsqlpackage-dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Bash@3
      displayName: Remove Image
      inputs:
        targetType: 'inline'
        script: |
            docker image prune -a -f
